# PHP
phpfpm:
  extends:
    file: php-fpm-5.6.yml
    service: phpfpm
  links:
    - db:db

# NGINX
nginx:
  image: nginx
  ports:
    - "8000:80"
  links:
    - phpfpm:phpfpm
  volumes:
    - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./app:/var/www/html
    - ./log/nginx:/var/log/nginx

# MYSQL
db:
  image: mysql
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
  volumes:
    - ./mysql/databases:/var/lib/mysql
    - ./mysql/dump:/docker-entrypoint-initdb.d
    - ./log/mysql:/var/log/mysql
